apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: cert-manager
  install:
    createNamespace: true
  chart:
    spec:
      chart: cert-manager
      version: v1.16.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: ingress-nginx
  install:
    createNamespace: true
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: external-secrets
  install:
    createNamespace: true
  chart:
    spec:
      chart: external-secrets
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
