apiVersion: v1
kind: Service
metadata:
  name: redis-rest
  labels:
    app.kubernetes.io/name: redis-rest
    app.kubernetes.io/component: cache-proxy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis-rest
    app.kubernetes.io/component: cache-proxy
  ports:
    - name: http
      port: 80
      targetPort: http
