apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: worldmonitor-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/apps
  prune: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: worldmonitor
  dependsOn:
    - name: worldmonitor-infra-configs
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: terraform-outputs
