apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: worldmonitor
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: worldmonitor
  git:
    checkout:
      ref:
        branch: kubernetes
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(kubernetes): automated image update [skip ci]

        {{ range .Changed.Changes }}{{ println .OldValue " -> " .NewValue }}{{ end }}
    push:
      branch: kubernetes
  update:
    path: ./kubernetes/apps/dashboard/overlays
    strategy: Setters
