apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: worldmonitor-full
  namespace: flux-system
spec:
  image: docker.io/syedhassanshah/worldmonitor
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: worldmonitor-tech
  namespace: flux-system
spec:
  image: docker.io/syedhassanshah/worldmonitor-tech
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: worldmonitor-finance
  namespace: flux-system
spec:
  image: docker.io/syedhassanshah/worldmonitor-finance
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: worldmonitor-happy
  namespace: flux-system
spec:
  image: docker.io/syedhassanshah/worldmonitor-happy
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: worldmonitor-commodity
  namespace: flux-system
spec:
  image: docker.io/syedhassanshah/worldmonitor-commodity
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: worldmonitor-energy
  namespace: flux-system
spec:
  image: docker.io/syedhassanshah/worldmonitor-energy
  interval: 5m
