apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: worldmonitor
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: kubernetes
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(kubernetes): automated image update [skip ci]

        {{ range .Updated.Images }}{{ println . }}{{ end }}
    push:
      branch: kubernetes
  update:
    path: ./kubernetes/dashboard/overlays
    strategy: Setters
