apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git-repository.yaml
  - image-repositories.yaml
  - image-policies.yaml
  - image-update-automation.yaml
  - dashboard-sync.yaml
